### ISSUE TITLE
piHPSDR version VU3RDD

### ISSUE THREAD

**Issue by UN7RX** [vu3rdd/pihpsdr#1]
Good afternoon, Ram! Is this your version of piHPSDR?
https://www.youtube.com/watch?v=0pO9re2Jr84
I've wanted to use piHPSDR for a long time, but unfortunately it has an inconvenient interface - small numbers, ugly arrangement of elements.
But your version is just wonderful! Can I download your version of piHPSDR somewhere?
Is this option in your repo?

**Comment by vu3rdd** [comment]
Hello Robert -- yes, code in this fork of pihpsdr is the one on that video on youtube. You may clone the repo and do `make` and `sudo make install` to run the pihpsdr. All the UI/font changes and many fixes in the CAT command handling etc are all in this fork. Please let me know if you need help building the code.

**Comment by UN7RX** [comment]
Great modification! Thank you very much!

**Comment by UN7RX** [comment]
I can't compile it. Gives the error .

pi@raspberrypi:~/pihpsdr $ make -j 4
fatal: Имена не найдены, не могу ничего описать.
Package libgpiod was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgpiod.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgpiod' found
gcc -g -Wno-deprecated-declarations      -D GPIO   -D LOCALCW     -D GIT_DATE='"2022-03-01"' -D GIT_VERSION='""'  `pkg-config --cflags gtk+-3.0` -c -o band.o band.c
gcc -g -Wno-deprecated-declarations      -D GPIO   -D LOCALCW     -D GIT_DATE='"2022-03-01"' -D GIT_VERSION='""'  `pkg-config --cflags gtk+-3.0` -c -o discovered.o discovered.c
gcc -g -Wno-deprecated-declarations      -D GPIO   -D LOCALCW     -D GIT_DATE='"2022-03-01"' -D GIT_VERSION='""'  `pkg-config --cflags gtk+-3.0` -c -o discovery.o discovery.c
gcc -g -Wno-deprecated-declarations      -D GPIO   -D LOCALCW     -D GIT_DATE='"2022-03-01"' -D GIT_VERSION='""'  `pkg-config --cflags gtk+-3.0` -c -o filter.o filter.c
In file included from sliders.h:22,
                 from filter.c:23:
receiver.h:26:10: fatal error: pulse/pulseaudio.h: Нет такого файла или каталога
 #include <pulse/pulseaudio.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from radio.h:26,
                 from band.c:30:
receiver.h:26:10: fatal error: pulse/pulseaudio.h: Нет такого файла или каталога
 #include <pulse/pulseaudio.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:228: band.o] Ошибка 1
make: *** Ожидание завершения заданий…
make: *** [Makefile:228: filter.o] Ошибка 1
In file included from radio.h:26,
                 from discovery.c:44:
receiver.h:26:10: fatal error: pulse/pulseaudio.h: Нет такого файла или каталога
 #include <pulse/pulseaudio.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:228: discovery.o] Ошибка 1
pi@raspberrypi:~/pihpsdr $

**Comment by UN7RX** [comment]
Solving the problem:
sudo apt-get install libpulse-dev

But there are new errors:
[url=https://ibb.co/zGTv5Yb][img]https://i.ibb.co/zGTv5Yb/2022-04-16-225243-800x480-scrot.png[/img][/url]

Why are there no errors in the original?

**Comment by UN7RX** [comment]
Ram, how do you install your version correctly? I would love to try it :(

**Comment by vu3rdd** [comment]
Hi Robert,

For the `i2c/smbus.h` I believe you need the kernel headers package installed. The reason why a freshly cloned pihpsdr from `g0orx/pihpsdr` compiles is because, GPIO support is disabled. For now, you may also try disabling them. I enabled it by default in the `Makefile` because of CW support. For now, please try commenting out [this line](https://github.com/vu3rdd/pihpsdr/blob/master/Makefile#L17). Hopefully that will solve the compilation issues.

Please let me know. And sorry for the late response.

73
Ram

**Comment by vu3rdd** [comment]
Hi Robert, don't worry, I perfectly understand your English. For me too, English is not the first language, so don't worry.

When you do the `make clean` that first line that starts with `fatal: ...` can be ignored. Don't worry about it. It does clean the binaries. 

Can you show the output when do you `make`?

**Comment by vu3rdd** [comment]
After the build, check the output of `ls` and see if you have the `pihpsdr` binary. That is all that matters. If it is found, you can invoke it `./pihpsdr`.

**Comment by vu3rdd** [comment]
I just pushed a change to the `Makefile` that fixes the "fatal: no names found" message.

**Comment by UN7RX** [comment]
when doing make clean:
pi@raspberrypi:~/pihpsdr $ make clean
rm -f *.o
rm -f pihpsdr hpsdrsim

when executing make there is an error at the end:
 -lrt -lm -lwdsp -lpthread -lpulse-simple -lpulse -lpulse-mainloop-glib  `pkg-config --libs gtk+-3.0` -lgpiod -li2c   
//usr/local/lib/libwdsp.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make: *** [Makefile:465: pihpsdr] Error 1

**Comment by vu3rdd** [comment]
> when doing make clean: pi@raspberrypi:~/pihpsdr $ make clean rm -f *.o rm -f pihpsdr hpsdrsim
> 
> when executing make there is an error at the end: -lrt -lm -lwdsp -lpthread -lpulse-simple -lpulse -lpulse-mainloop-glib `pkg-config --libs gtk+-3.0` -lgpiod -li2c //usr/local/lib/libwdsp.so: file not recognized: file format not recognized collect2: error: ld returned 1 exit status make: *** [Makefile:465: pihpsdr] Error 1

That is strange? Please do two things:
1. Please paste the output of this command: `file /usr/local/lib/libwdsp.so`
2. Please re-clone wdsp from [g0orx/wdsp](https://github.com/g0orx/wdsp) and re-build it from source and then come back to pihpsdr and do a `make` again.

```
git clone https://github.com/g0orx/wdsp
cd wdsp
make
sudo make install
```

and then go to the directory where you cloned pihpsdr:
```
cd pihpsdr
make
make install
```
If it can be a help, we can setup a video chat or something where you can project your screen and we can debug this together. I would really like you to get to run it and it is not very complicated. My email address is `ram@rkrishnan.org`. Do let me know how it goes.

**Comment by UN7RX** [comment]
Hello Ram!
Sorry that I did not reply for a while. Yesterday the SSD drive failed, I had to install the OS again and everything else.
I finally got your version of piHPSDR up and running.
A little information.
Last time and now I immediately install all the necessary packages that are required for the piHPSDR version of g0orx. Here are the packages:
sudo apt-get install git
sudo apt-get install pkg-config
sudo apt-get install libfftw3-dev
sudo apt-get install libgtk-3-dev
sudo apt-get install libasound2-dev
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install wiringpi
git clone https://github.com/g0orx/wdsp

 His version compiles and runs fine.
But in order for your version to work, you need to install two more packages:
 sudo apt-get install libpulse-dev
sudo apt-get install libgpiod-dev

Then there are no errors during compilation and everything is assembled correctly. And be sure to install and compile the package from the repository after that
 https://github.com/g0orx/wdsp
It should be noted for those who will repeat your version.
I really liked your design. Just great. I can write x86 assembler, C#, VB, some PureBasic, Delphi. But I don't know C at all
Been wanting to change the design for a long time, you did it! ))) You can make it a little more beautiful, different colors, the analog S meter is a little thicker, brighter. In any case, now it is a full-fledged interface for a stand-alone transceiver.
Tell me which pihpsdr executable file should be run correctly, which is in the pi/pihpsdr folder or in the pi/pihpsdr/release/pihpsdr folder? The first one starts without any questions, cleanly. The second, as in the g0orx version, makes a lot of requests.

**Comment by UN7RX** [comment]
This is my future version of the DDC DUC transceiver:
![20220420_012125](https://user-images.githubusercontent.com/56934660/164080152-15f00c9d-2b25-40fb-bd13-44855961d9f8.jpg)

![20220420_011503](https://user-images.githubusercontent.com/56934660/164080300-fc7f1e6d-4f1e-421d-b916-65f39bcdee28.jpg)

![2022-04-19-223120_1024x600_scrot](https://user-images.githubusercontent.com/56934660/164080362-3e6e7c19-1c57-40d4-ac08-1aedcb85e873.png)

**Comment by UN7RX** [comment]
Ram, I'm sorry, I just saw it now. And where did the items for assigning functions for encoders and buttons, for the MK_II controller, disappear in the menu ???

**Comment by UN7RX** [comment]
Ram, I'm sorry, I just saw it now. And where did the items for assigning functions for encoders and buttons, for the MK_II controller, disappear in the menu ???

**Comment by UN7RX** [comment]
Ram, I'm sorry, I just saw it now. And where did the items for assigning functions for encoders and buttons, for the MK_II controller, disappear in the menu ???

**Comment by UN7RX** [comment]
Probably there will be no Probably there will be no answer ... Ok, thanks, good luck!answer ... Ok, thanks, good luck!

**Comment by vu3rdd** [comment]
> Probably there will be no Probably there will be no answer ... Ok, thanks, good luck!answer ... Ok, thanks, good luck!

Sorry Robert for the delay. I haven't touched any of the encoder/button related parts of the code since I am using a different controller board designed by my friend Gopakumar VU2XTO. But let me take a quick look now..

**Comment by vu3rdd** [comment]
The encoder menu should disappear only if GPIO is disabled in the Makefile. But I see that it is enabled in [our Makefile](https://github.com/vu3rdd/pihpsdr/blob/master/Makefile#L17). Can you please check in your copy of the code if this is the case?

**Comment by vu3rdd** [comment]
One more thing you can try is [changing this line in discovery.c](https://github.com/vu3rdd/pihpsdr/blob/master/discovery.c#L566) from `NO_CONTROLLER` to `CONTROLLER2_V2` or whatever you want it to be and recompile the code.

**Comment by UN7RX** [comment]
Once again, my condolences, Ram. I also went through this once.
And thank you for your help!

**Comment by UN7RX** [comment]
I checked the Makefile. GPIO enabled. Changed NO_CONTROLLER to CONTROLLER2_V2 in the discovery.c file.
But still, there are no encoders or switches in the menu (
![2022-05-29-175323_1024x600_scrot](https://user-images.githubusercontent.com/56934660/170867871-39886474-dfe2-4f57-bb46-d796b965a497.png)
(

**Comment by vu3rdd** [comment]
OK, thanks for the info. Let me play around with it a bit today.

**Comment by UN7RX** [comment]
Hello Ram!
Have you found the reason for the loss of the menu of the settings of the buttons and the encoder?

**Comment by vu3rdd** [comment]
Hi Robert, Yes, I managed to find the issue. Go to this line on discovery.c and change it to the controller you have (three choices, `CONTROLLER1`, `CONTROLLER2_V1`, `CONTROLLER2_V2`) and recompile (`make`) and then the switches and encoders appear in the menu.

**Comment by vu3rdd** [comment]
Once you confirm, I will close this issue.

**Comment by UN7RX** [comment]
Thank you! I will try to check it as soon as possible and let you know!

**Comment by UN7RX** [comment]
Good afternoon Ram! I recompiled the sources, everything is great! Buttons and encoders appeared in the menu!
Thanks a lot for your patience and help! Now you can continue to work on the transceiver)))) Do the rest of the circuit.

**Comment by vu3rdd** [comment]
Great. Will close this issue then. Thanks.
